// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWFAnUtLk_yc4snNGPpPuM3eD216istW8',
    appId: '1:77435319006:web:56f68ab3deacf259ba884f',
    messagingSenderId: '77435319006',
    projectId: 'kedeapp-371c2',
    authDomain: 'kedeapp-371c2.firebaseapp.com',
    storageBucket: 'kedeapp-371c2.firebasestorage.app',
    measurementId: 'G-V4P0H9VVDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPhH7IkLn3bTY1mrMttrVT6wvTTC-UKdg',
    appId: '1:77435319006:android:c04d4f0d7cd62600ba884f',
    messagingSenderId: '77435319006',
    projectId: 'kedeapp-371c2',
    storageBucket: 'kedeapp-371c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGt7m0Xg6Tb5qEQqLx9T4-ld7pjDrbpUM',
    appId: '1:77435319006:ios:8a5cd3dfb3fc50baba884f',
    messagingSenderId: '77435319006',
    projectId: 'kedeapp-371c2',
    storageBucket: 'kedeapp-371c2.firebasestorage.app',
    iosBundleId: 'com.example.kede',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGt7m0Xg6Tb5qEQqLx9T4-ld7pjDrbpUM',
    appId: '1:77435319006:ios:8a5cd3dfb3fc50baba884f',
    messagingSenderId: '77435319006',
    projectId: 'kedeapp-371c2',
    storageBucket: 'kedeapp-371c2.firebasestorage.app',
    iosBundleId: 'com.example.kede',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWFAnUtLk_yc4snNGPpPuM3eD216istW8',
    appId: '1:77435319006:web:8fd59fab089090c0ba884f',
    messagingSenderId: '77435319006',
    projectId: 'kedeapp-371c2',
    authDomain: 'kedeapp-371c2.firebaseapp.com',
    storageBucket: 'kedeapp-371c2.firebasestorage.app',
    measurementId: 'G-FCRKGMXY66',
  );
}
